// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: catalog/v1/service.proto

package catalogv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_catalog_v1_service_proto protoreflect.FileDescriptor

const file_catalog_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x18catalog/v1/service.proto\x12\n" +
	"catalog.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x19catalog/v1/messages.proto2\xe7\f\n" +
	"\x0eCatalogService\x12e\n" +
	"\vCreateStore\x12\x1e.catalog.v1.CreateStoreRequest\x1a\x1f.catalog.v1.CreateStoreResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/stores\x12u\n" +
	"\vUpdateStore\x12\x1e.catalog.v1.UpdateStoreRequest\x1a\x1f.catalog.v1.UpdateStoreResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x06update2\x15/v1/stores/{store_id}\x12m\n" +
	"\vDeleteStore\x12\x1e.catalog.v1.DeleteStoreRequest\x1a\x1f.catalog.v1.DeleteStoreResponse\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/v1/stores/{store_id}\x12d\n" +
	"\bGetStore\x12\x1b.catalog.v1.GetStoreRequest\x1a\x1c.catalog.v1.GetStoreResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/stores/{store_id}\x12_\n" +
	"\n" +
	"ListStores\x12\x1d.catalog.v1.ListStoresRequest\x1a\x1e.catalog.v1.ListStoresResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/stores\x12o\n" +
	"\x0eCreateCategory\x12!.catalog.v1.CreateCategoryRequest\x1a\".catalog.v1.CreateCategoryResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/categories\x12\x85\x01\n" +
	"\x0eUpdateCategory\x12!.catalog.v1.UpdateCategoryRequest\x1a\".catalog.v1.UpdateCategoryResponse\",\x82\xd3\xe4\x93\x02&:\x06update2\x1c/v1/categories/{category_id}\x12}\n" +
	"\x0eDeleteCategory\x12!.catalog.v1.DeleteCategoryRequest\x1a\".catalog.v1.DeleteCategoryResponse\"$\x82\xd3\xe4\x93\x02\x1e*\x1c/v1/categories/{category_id}\x12t\n" +
	"\vGetCategory\x12\x1e.catalog.v1.GetCategoryRequest\x1a\x1f.catalog.v1.GetCategoryResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/categories/{category_id}\x12z\n" +
	"\x0eListCategories\x12!.catalog.v1.ListCategoriesRequest\x1a\".catalog.v1.ListCategoriesResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/categories/{store_id}\x12m\n" +
	"\rCreateProduct\x12 .catalog.v1.CreateProductRequest\x1a!.catalog.v1.CreateProductResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/products\x12\x7f\n" +
	"\rUpdateProduct\x12 .catalog.v1.UpdateProductRequest\x1a!.catalog.v1.UpdateProductResponse\")\x82\xd3\xe4\x93\x02#:\x06update2\x19/v1/products/{product_id}\x12w\n" +
	"\rDeleteProduct\x12 .catalog.v1.DeleteProductRequest\x1a!.catalog.v1.DeleteProductResponse\"!\x82\xd3\xe4\x93\x02\x1b*\x19/v1/products/{product_id}\x12n\n" +
	"\n" +
	"GetProduct\x12\x1d.catalog.v1.GetProductRequest\x1a\x1e.catalog.v1.GetProductResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/products/{product_id}B\xf1\x01\x92AD\x12>\n" +
	"\x15Linko Catalog Service\" \n" +
	"\n" +
	"Ivan Popov\x1a\x12vanap387@gmail.com2\x031.0*\x02\x01\x02\n" +
	"\x0ecom.catalog.v1B\fServiceProtoP\x01ZAgithub.com/escoutdoor/linko/common/pkg/proto/catalog/v1;catalogv1\xa2\x02\x03CXX\xaa\x02\n" +
	"Catalog.V1\xca\x02\n" +
	"Catalog\\V1\xe2\x02\x16Catalog\\V1\\GPBMetadata\xea\x02\vCatalog::V1b\x06proto3"

var file_catalog_v1_service_proto_goTypes = []any{
	(*CreateStoreRequest)(nil),     // 0: catalog.v1.CreateStoreRequest
	(*UpdateStoreRequest)(nil),     // 1: catalog.v1.UpdateStoreRequest
	(*DeleteStoreRequest)(nil),     // 2: catalog.v1.DeleteStoreRequest
	(*GetStoreRequest)(nil),        // 3: catalog.v1.GetStoreRequest
	(*ListStoresRequest)(nil),      // 4: catalog.v1.ListStoresRequest
	(*CreateCategoryRequest)(nil),  // 5: catalog.v1.CreateCategoryRequest
	(*UpdateCategoryRequest)(nil),  // 6: catalog.v1.UpdateCategoryRequest
	(*DeleteCategoryRequest)(nil),  // 7: catalog.v1.DeleteCategoryRequest
	(*GetCategoryRequest)(nil),     // 8: catalog.v1.GetCategoryRequest
	(*ListCategoriesRequest)(nil),  // 9: catalog.v1.ListCategoriesRequest
	(*CreateProductRequest)(nil),   // 10: catalog.v1.CreateProductRequest
	(*UpdateProductRequest)(nil),   // 11: catalog.v1.UpdateProductRequest
	(*DeleteProductRequest)(nil),   // 12: catalog.v1.DeleteProductRequest
	(*GetProductRequest)(nil),      // 13: catalog.v1.GetProductRequest
	(*CreateStoreResponse)(nil),    // 14: catalog.v1.CreateStoreResponse
	(*UpdateStoreResponse)(nil),    // 15: catalog.v1.UpdateStoreResponse
	(*DeleteStoreResponse)(nil),    // 16: catalog.v1.DeleteStoreResponse
	(*GetStoreResponse)(nil),       // 17: catalog.v1.GetStoreResponse
	(*ListStoresResponse)(nil),     // 18: catalog.v1.ListStoresResponse
	(*CreateCategoryResponse)(nil), // 19: catalog.v1.CreateCategoryResponse
	(*UpdateCategoryResponse)(nil), // 20: catalog.v1.UpdateCategoryResponse
	(*DeleteCategoryResponse)(nil), // 21: catalog.v1.DeleteCategoryResponse
	(*GetCategoryResponse)(nil),    // 22: catalog.v1.GetCategoryResponse
	(*ListCategoriesResponse)(nil), // 23: catalog.v1.ListCategoriesResponse
	(*CreateProductResponse)(nil),  // 24: catalog.v1.CreateProductResponse
	(*UpdateProductResponse)(nil),  // 25: catalog.v1.UpdateProductResponse
	(*DeleteProductResponse)(nil),  // 26: catalog.v1.DeleteProductResponse
	(*GetProductResponse)(nil),     // 27: catalog.v1.GetProductResponse
}
var file_catalog_v1_service_proto_depIdxs = []int32{
	0,  // 0: catalog.v1.CatalogService.CreateStore:input_type -> catalog.v1.CreateStoreRequest
	1,  // 1: catalog.v1.CatalogService.UpdateStore:input_type -> catalog.v1.UpdateStoreRequest
	2,  // 2: catalog.v1.CatalogService.DeleteStore:input_type -> catalog.v1.DeleteStoreRequest
	3,  // 3: catalog.v1.CatalogService.GetStore:input_type -> catalog.v1.GetStoreRequest
	4,  // 4: catalog.v1.CatalogService.ListStores:input_type -> catalog.v1.ListStoresRequest
	5,  // 5: catalog.v1.CatalogService.CreateCategory:input_type -> catalog.v1.CreateCategoryRequest
	6,  // 6: catalog.v1.CatalogService.UpdateCategory:input_type -> catalog.v1.UpdateCategoryRequest
	7,  // 7: catalog.v1.CatalogService.DeleteCategory:input_type -> catalog.v1.DeleteCategoryRequest
	8,  // 8: catalog.v1.CatalogService.GetCategory:input_type -> catalog.v1.GetCategoryRequest
	9,  // 9: catalog.v1.CatalogService.ListCategories:input_type -> catalog.v1.ListCategoriesRequest
	10, // 10: catalog.v1.CatalogService.CreateProduct:input_type -> catalog.v1.CreateProductRequest
	11, // 11: catalog.v1.CatalogService.UpdateProduct:input_type -> catalog.v1.UpdateProductRequest
	12, // 12: catalog.v1.CatalogService.DeleteProduct:input_type -> catalog.v1.DeleteProductRequest
	13, // 13: catalog.v1.CatalogService.GetProduct:input_type -> catalog.v1.GetProductRequest
	14, // 14: catalog.v1.CatalogService.CreateStore:output_type -> catalog.v1.CreateStoreResponse
	15, // 15: catalog.v1.CatalogService.UpdateStore:output_type -> catalog.v1.UpdateStoreResponse
	16, // 16: catalog.v1.CatalogService.DeleteStore:output_type -> catalog.v1.DeleteStoreResponse
	17, // 17: catalog.v1.CatalogService.GetStore:output_type -> catalog.v1.GetStoreResponse
	18, // 18: catalog.v1.CatalogService.ListStores:output_type -> catalog.v1.ListStoresResponse
	19, // 19: catalog.v1.CatalogService.CreateCategory:output_type -> catalog.v1.CreateCategoryResponse
	20, // 20: catalog.v1.CatalogService.UpdateCategory:output_type -> catalog.v1.UpdateCategoryResponse
	21, // 21: catalog.v1.CatalogService.DeleteCategory:output_type -> catalog.v1.DeleteCategoryResponse
	22, // 22: catalog.v1.CatalogService.GetCategory:output_type -> catalog.v1.GetCategoryResponse
	23, // 23: catalog.v1.CatalogService.ListCategories:output_type -> catalog.v1.ListCategoriesResponse
	24, // 24: catalog.v1.CatalogService.CreateProduct:output_type -> catalog.v1.CreateProductResponse
	25, // 25: catalog.v1.CatalogService.UpdateProduct:output_type -> catalog.v1.UpdateProductResponse
	26, // 26: catalog.v1.CatalogService.DeleteProduct:output_type -> catalog.v1.DeleteProductResponse
	27, // 27: catalog.v1.CatalogService.GetProduct:output_type -> catalog.v1.GetProductResponse
	14, // [14:28] is the sub-list for method output_type
	0,  // [0:14] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_catalog_v1_service_proto_init() }
func file_catalog_v1_service_proto_init() {
	if File_catalog_v1_service_proto != nil {
		return
	}
	file_catalog_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_v1_service_proto_rawDesc), len(file_catalog_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_v1_service_proto_goTypes,
		DependencyIndexes: file_catalog_v1_service_proto_depIdxs,
	}.Build()
	File_catalog_v1_service_proto = out.File
	file_catalog_v1_service_proto_goTypes = nil
	file_catalog_v1_service_proto_depIdxs = nil
}
