// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: role/v1/service.proto

package rolev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_role_v1_service_proto protoreflect.FileDescriptor

const file_role_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x15role/v1/service.proto\x12\arole.v1\x1a\x16role/v1/messages.proto2\x9d\x02\n" +
	"\vRoleService\x12E\n" +
	"\n" +
	"CreateRole\x12\x1a.role.v1.CreateRoleRequest\x1a\x1b.role.v1.CreateRoleResponse\x12<\n" +
	"\aGetRole\x12\x17.role.v1.GetRoleRequest\x1a\x18.role.v1.GetRoleResponse\x12B\n" +
	"\tListRoles\x12\x19.role.v1.ListRolesRequest\x1a\x1a.role.v1.ListRolesResponse\x12E\n" +
	"\n" +
	"DeleteRole\x12\x1a.role.v1.DeleteRoleRequest\x1a\x1b.role.v1.DeleteRoleResponseB\x95\x01\n" +
	"\vcom.role.v1B\fServiceProtoP\x01Z;github.com/escoutdoor/linko/common/pkg/proto/role/v1;rolev1\xa2\x02\x03RXX\xaa\x02\aRole.V1\xca\x02\aRole\\V1\xe2\x02\x13Role\\V1\\GPBMetadata\xea\x02\bRole::V1b\x06proto3"

var file_role_v1_service_proto_goTypes = []any{
	(*CreateRoleRequest)(nil),  // 0: role.v1.CreateRoleRequest
	(*GetRoleRequest)(nil),     // 1: role.v1.GetRoleRequest
	(*ListRolesRequest)(nil),   // 2: role.v1.ListRolesRequest
	(*DeleteRoleRequest)(nil),  // 3: role.v1.DeleteRoleRequest
	(*CreateRoleResponse)(nil), // 4: role.v1.CreateRoleResponse
	(*GetRoleResponse)(nil),    // 5: role.v1.GetRoleResponse
	(*ListRolesResponse)(nil),  // 6: role.v1.ListRolesResponse
	(*DeleteRoleResponse)(nil), // 7: role.v1.DeleteRoleResponse
}
var file_role_v1_service_proto_depIdxs = []int32{
	0, // 0: role.v1.RoleService.CreateRole:input_type -> role.v1.CreateRoleRequest
	1, // 1: role.v1.RoleService.GetRole:input_type -> role.v1.GetRoleRequest
	2, // 2: role.v1.RoleService.ListRoles:input_type -> role.v1.ListRolesRequest
	3, // 3: role.v1.RoleService.DeleteRole:input_type -> role.v1.DeleteRoleRequest
	4, // 4: role.v1.RoleService.CreateRole:output_type -> role.v1.CreateRoleResponse
	5, // 5: role.v1.RoleService.GetRole:output_type -> role.v1.GetRoleResponse
	6, // 6: role.v1.RoleService.ListRoles:output_type -> role.v1.ListRolesResponse
	7, // 7: role.v1.RoleService.DeleteRole:output_type -> role.v1.DeleteRoleResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_role_v1_service_proto_init() }
func file_role_v1_service_proto_init() {
	if File_role_v1_service_proto != nil {
		return
	}
	file_role_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_role_v1_service_proto_rawDesc), len(file_role_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_role_v1_service_proto_goTypes,
		DependencyIndexes: file_role_v1_service_proto_depIdxs,
	}.Build()
	File_role_v1_service_proto = out.File
	file_role_v1_service_proto_goTypes = nil
	file_role_v1_service_proto_depIdxs = nil
}
