// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: user/v1/service.proto

package userv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_user_v1_service_proto protoreflect.FileDescriptor

const file_user_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x15user/v1/service.proto\x12\auser.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x16user/v1/messages.proto2\xd4\x01\n" +
	"\vUserService\x12Y\n" +
	"\aGetUser\x12\x17.user.v1.GetUserRequest\x1a\x18.user.v1.GetUserResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/users/{user_id}\x12j\n" +
	"\n" +
	"UpdateUser\x12\x1a.user.v1.UpdateUserRequest\x1a\x1b.user.v1.UpdateUserResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x06update2\x13/v1/users/{user_id}B\xd9\x01\x92AA\x12;\n" +
	"\x12Linko User Service\" \n" +
	"\n" +
	"Ivan Popov\x1a\x12vanap387@gmail.com2\x031.0*\x02\x01\x02\n" +
	"\vcom.user.v1B\fServiceProtoP\x01Z;github.com/escoutdoor/linko/common/pkg/proto/user/v1;userv1\xa2\x02\x03UXX\xaa\x02\aUser.V1\xca\x02\aUser\\V1\xe2\x02\x13User\\V1\\GPBMetadata\xea\x02\bUser::V1b\x06proto3"

var file_user_v1_service_proto_goTypes = []any{
	(*GetUserRequest)(nil),     // 0: user.v1.GetUserRequest
	(*UpdateUserRequest)(nil),  // 1: user.v1.UpdateUserRequest
	(*GetUserResponse)(nil),    // 2: user.v1.GetUserResponse
	(*UpdateUserResponse)(nil), // 3: user.v1.UpdateUserResponse
}
var file_user_v1_service_proto_depIdxs = []int32{
	0, // 0: user.v1.UserService.GetUser:input_type -> user.v1.GetUserRequest
	1, // 1: user.v1.UserService.UpdateUser:input_type -> user.v1.UpdateUserRequest
	2, // 2: user.v1.UserService.GetUser:output_type -> user.v1.GetUserResponse
	3, // 3: user.v1.UserService.UpdateUser:output_type -> user.v1.UpdateUserResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_v1_service_proto_init() }
func file_user_v1_service_proto_init() {
	if File_user_v1_service_proto != nil {
		return
	}
	file_user_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_service_proto_rawDesc), len(file_user_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_service_proto_goTypes,
		DependencyIndexes: file_user_v1_service_proto_depIdxs,
	}.Build()
	File_user_v1_service_proto = out.File
	file_user_v1_service_proto_goTypes = nil
	file_user_v1_service_proto_depIdxs = nil
}
