// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: driver/v1/messages.proto

package driverv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Driver struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifier of the driver
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The identifier of the user connected to this driver account
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The rating of the driver
	Rating float32 `protobuf:"fixed32,3,opt,name=rating,proto3" json:"rating,omitempty"`
	// Review count
	ReviewCount int32 `protobuf:"varint,4,opt,name=review_count,json=reviewCount,proto3" json:"review_count,omitempty"`
	// Date of creation
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Date of the latest update
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Driver) Reset() {
	*x = Driver{}
	mi := &file_driver_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Driver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Driver) ProtoMessage() {}

func (x *Driver) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Driver.ProtoReflect.Descriptor instead.
func (*Driver) Descriptor() ([]byte, []int) {
	return file_driver_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Driver) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Driver) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Driver) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Driver) GetReviewCount() int32 {
	if x != nil {
		return x.ReviewCount
	}
	return 0
}

func (x *Driver) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Driver) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateDriverRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifier of the user to connect with
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDriverRequest) Reset() {
	*x = CreateDriverRequest{}
	mi := &file_driver_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDriverRequest) ProtoMessage() {}

func (x *CreateDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDriverRequest.ProtoReflect.Descriptor instead.
func (*CreateDriverRequest) Descriptor() ([]byte, []int) {
	return file_driver_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDriverRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateDriverResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Created driver profile
	Driver        *Driver `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDriverResponse) Reset() {
	*x = CreateDriverResponse{}
	mi := &file_driver_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDriverResponse) ProtoMessage() {}

func (x *CreateDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDriverResponse.ProtoReflect.Descriptor instead.
func (*CreateDriverResponse) Descriptor() ([]byte, []int) {
	return file_driver_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDriverResponse) GetDriver() *Driver {
	if x != nil {
		return x.Driver
	}
	return nil
}

type DriverUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverUpdate) Reset() {
	*x = DriverUpdate{}
	mi := &file_driver_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverUpdate) ProtoMessage() {}

func (x *DriverUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverUpdate.ProtoReflect.Descriptor instead.
func (*DriverUpdate) Descriptor() ([]byte, []int) {
	return file_driver_v1_messages_proto_rawDescGZIP(), []int{3}
}

type UpdateDriverRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The id of the driver to update
	DriverId string `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	// Values
	Update *DriverUpdate `protobuf:"bytes,2,opt,name=update,proto3" json:"update,omitempty"`
	// The fields to update
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverRequest) Reset() {
	*x = UpdateDriverRequest{}
	mi := &file_driver_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverRequest) ProtoMessage() {}

func (x *UpdateDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverRequest.ProtoReflect.Descriptor instead.
func (*UpdateDriverRequest) Descriptor() ([]byte, []int) {
	return file_driver_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateDriverRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *UpdateDriverRequest) GetUpdate() *DriverUpdate {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *UpdateDriverRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateDriverResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated driver
	Driver        *Driver `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverResponse) Reset() {
	*x = UpdateDriverResponse{}
	mi := &file_driver_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverResponse) ProtoMessage() {}

func (x *UpdateDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverResponse.ProtoReflect.Descriptor instead.
func (*UpdateDriverResponse) Descriptor() ([]byte, []int) {
	return file_driver_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateDriverResponse) GetDriver() *Driver {
	if x != nil {
		return x.Driver
	}
	return nil
}

type GetDriverRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The id of the driver to retrieve
	DriverId      string `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverRequest) Reset() {
	*x = GetDriverRequest{}
	mi := &file_driver_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverRequest) ProtoMessage() {}

func (x *GetDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverRequest.ProtoReflect.Descriptor instead.
func (*GetDriverRequest) Descriptor() ([]byte, []int) {
	return file_driver_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *GetDriverRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type GetDriverResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The retrieved driver
	Driver        *Driver `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverResponse) Reset() {
	*x = GetDriverResponse{}
	mi := &file_driver_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverResponse) ProtoMessage() {}

func (x *GetDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverResponse.ProtoReflect.Descriptor instead.
func (*GetDriverResponse) Descriptor() ([]byte, []int) {
	return file_driver_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *GetDriverResponse) GetDriver() *Driver {
	if x != nil {
		return x.Driver
	}
	return nil
}

type ListDriversRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriversRequest) Reset() {
	*x = ListDriversRequest{}
	mi := &file_driver_v1_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriversRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriversRequest) ProtoMessage() {}

func (x *ListDriversRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriversRequest.ProtoReflect.Descriptor instead.
func (*ListDriversRequest) Descriptor() ([]byte, []int) {
	return file_driver_v1_messages_proto_rawDescGZIP(), []int{8}
}

type ListDriversResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of drivers
	Drivers       []*Driver `protobuf:"bytes,1,rep,name=drivers,proto3" json:"drivers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriversResponse) Reset() {
	*x = ListDriversResponse{}
	mi := &file_driver_v1_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriversResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriversResponse) ProtoMessage() {}

func (x *ListDriversResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriversResponse.ProtoReflect.Descriptor instead.
func (*ListDriversResponse) Descriptor() ([]byte, []int) {
	return file_driver_v1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *ListDriversResponse) GetDrivers() []*Driver {
	if x != nil {
		return x.Drivers
	}
	return nil
}

type DeleteDriverRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The id of the driver to delete
	DriverId      string `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDriverRequest) Reset() {
	*x = DeleteDriverRequest{}
	mi := &file_driver_v1_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDriverRequest) ProtoMessage() {}

func (x *DeleteDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDriverRequest.ProtoReflect.Descriptor instead.
func (*DeleteDriverRequest) Descriptor() ([]byte, []int) {
	return file_driver_v1_messages_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteDriverRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type DeleteDriverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDriverResponse) Reset() {
	*x = DeleteDriverResponse{}
	mi := &file_driver_v1_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDriverResponse) ProtoMessage() {}

func (x *DeleteDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDriverResponse.ProtoReflect.Descriptor instead.
func (*DeleteDriverResponse) Descriptor() ([]byte, []int) {
	return file_driver_v1_messages_proto_rawDescGZIP(), []int{11}
}

var File_driver_v1_messages_proto protoreflect.FileDescriptor

const file_driver_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x18driver/v1/messages.proto\x12\tdriver.v1\x1a\x1bbuf/validate/validate.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe2\x01\n" +
	"\x06Driver\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x02R\x06rating\x12!\n" +
	"\freview_count\x18\x04 \x01(\x05R\vreviewCount\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"8\n" +
	"\x13CreateDriverRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\"A\n" +
	"\x14CreateDriverResponse\x12)\n" +
	"\x06driver\x18\x01 \x01(\v2\x11.driver.v1.DriverR\x06driver\"\x0e\n" +
	"\fDriverUpdate\"\xaa\x01\n" +
	"\x13UpdateDriverRequest\x12%\n" +
	"\tdriver_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\bdriverId\x12/\n" +
	"\x06update\x18\x02 \x01(\v2\x17.driver.v1.DriverUpdateR\x06update\x12;\n" +
	"\vupdate_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"A\n" +
	"\x14UpdateDriverResponse\x12)\n" +
	"\x06driver\x18\x01 \x01(\v2\x11.driver.v1.DriverR\x06driver\"9\n" +
	"\x10GetDriverRequest\x12%\n" +
	"\tdriver_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\bdriverId\">\n" +
	"\x11GetDriverResponse\x12)\n" +
	"\x06driver\x18\x01 \x01(\v2\x11.driver.v1.DriverR\x06driver\"\x14\n" +
	"\x12ListDriversRequest\"B\n" +
	"\x13ListDriversResponse\x12+\n" +
	"\adrivers\x18\x01 \x03(\v2\x11.driver.v1.DriverR\adrivers\"<\n" +
	"\x13DeleteDriverRequest\x12%\n" +
	"\tdriver_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\bdriverId\"\x16\n" +
	"\x14DeleteDriverResponseB\xa4\x01\n" +
	"\rcom.driver.v1B\rMessagesProtoP\x01Z?github.com/escoutdoor/linko/common/pkg/proto/driver/v1;driverv1\xa2\x02\x03DXX\xaa\x02\tDriver.V1\xca\x02\tDriver\\V1\xe2\x02\x15Driver\\V1\\GPBMetadata\xea\x02\n" +
	"Driver::V1b\x06proto3"

var (
	file_driver_v1_messages_proto_rawDescOnce sync.Once
	file_driver_v1_messages_proto_rawDescData []byte
)

func file_driver_v1_messages_proto_rawDescGZIP() []byte {
	file_driver_v1_messages_proto_rawDescOnce.Do(func() {
		file_driver_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_driver_v1_messages_proto_rawDesc), len(file_driver_v1_messages_proto_rawDesc)))
	})
	return file_driver_v1_messages_proto_rawDescData
}

var file_driver_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_driver_v1_messages_proto_goTypes = []any{
	(*Driver)(nil),                // 0: driver.v1.Driver
	(*CreateDriverRequest)(nil),   // 1: driver.v1.CreateDriverRequest
	(*CreateDriverResponse)(nil),  // 2: driver.v1.CreateDriverResponse
	(*DriverUpdate)(nil),          // 3: driver.v1.DriverUpdate
	(*UpdateDriverRequest)(nil),   // 4: driver.v1.UpdateDriverRequest
	(*UpdateDriverResponse)(nil),  // 5: driver.v1.UpdateDriverResponse
	(*GetDriverRequest)(nil),      // 6: driver.v1.GetDriverRequest
	(*GetDriverResponse)(nil),     // 7: driver.v1.GetDriverResponse
	(*ListDriversRequest)(nil),    // 8: driver.v1.ListDriversRequest
	(*ListDriversResponse)(nil),   // 9: driver.v1.ListDriversResponse
	(*DeleteDriverRequest)(nil),   // 10: driver.v1.DeleteDriverRequest
	(*DeleteDriverResponse)(nil),  // 11: driver.v1.DeleteDriverResponse
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil), // 13: google.protobuf.FieldMask
}
var file_driver_v1_messages_proto_depIdxs = []int32{
	12, // 0: driver.v1.Driver.created_at:type_name -> google.protobuf.Timestamp
	12, // 1: driver.v1.Driver.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: driver.v1.CreateDriverResponse.driver:type_name -> driver.v1.Driver
	3,  // 3: driver.v1.UpdateDriverRequest.update:type_name -> driver.v1.DriverUpdate
	13, // 4: driver.v1.UpdateDriverRequest.update_mask:type_name -> google.protobuf.FieldMask
	0,  // 5: driver.v1.UpdateDriverResponse.driver:type_name -> driver.v1.Driver
	0,  // 6: driver.v1.GetDriverResponse.driver:type_name -> driver.v1.Driver
	0,  // 7: driver.v1.ListDriversResponse.drivers:type_name -> driver.v1.Driver
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_driver_v1_messages_proto_init() }
func file_driver_v1_messages_proto_init() {
	if File_driver_v1_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_driver_v1_messages_proto_rawDesc), len(file_driver_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_driver_v1_messages_proto_goTypes,
		DependencyIndexes: file_driver_v1_messages_proto_depIdxs,
		MessageInfos:      file_driver_v1_messages_proto_msgTypes,
	}.Build()
	File_driver_v1_messages_proto = out.File
	file_driver_v1_messages_proto_goTypes = nil
	file_driver_v1_messages_proto_depIdxs = nil
}
