// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: driver/v1/service.proto

package driverv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_driver_v1_service_proto protoreflect.FileDescriptor

const file_driver_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x17driver/v1/service.proto\x12\tdriver.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x18driver/v1/messages.proto2\xb0\x04\n" +
	"\rDriverService\x12g\n" +
	"\fCreateDriver\x12\x1e.driver.v1.CreateDriverRequest\x1a\x1f.driver.v1.CreateDriverResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/drivers\x12x\n" +
	"\fUpdateDriver\x12\x1e.driver.v1.UpdateDriverRequest\x1a\x1f.driver.v1.UpdateDriverResponse\"'\x82\xd3\xe4\x93\x02!:\x06update2\x17/v1/drivers/{driver_id}\x12g\n" +
	"\tGetDriver\x12\x1b.driver.v1.GetDriverRequest\x1a\x1c.driver.v1.GetDriverResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/drivers/{driver_id}\x12a\n" +
	"\vListDrivers\x12\x1d.driver.v1.ListDriversRequest\x1a\x1e.driver.v1.ListDriversResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/drivers\x12p\n" +
	"\fDeleteDriver\x12\x1e.driver.v1.DeleteDriverRequest\x1a\x1f.driver.v1.DeleteDriverResponse\"\x1f\x82\xd3\xe4\x93\x02\x19*\x17/v1/drivers/{driver_id}B\xe9\x01\x92AC\x12=\n" +
	"\x14Linko Driver Service\" \n" +
	"\n" +
	"Ivan Popov\x1a\x12vanap387@gmail.com2\x031.0*\x02\x01\x02\n" +
	"\rcom.driver.v1B\fServiceProtoP\x01Z?github.com/escoutdoor/linko/common/pkg/proto/driver/v1;driverv1\xa2\x02\x03DXX\xaa\x02\tDriver.V1\xca\x02\tDriver\\V1\xe2\x02\x15Driver\\V1\\GPBMetadata\xea\x02\n" +
	"Driver::V1b\x06proto3"

var file_driver_v1_service_proto_goTypes = []any{
	(*CreateDriverRequest)(nil),  // 0: driver.v1.CreateDriverRequest
	(*UpdateDriverRequest)(nil),  // 1: driver.v1.UpdateDriverRequest
	(*GetDriverRequest)(nil),     // 2: driver.v1.GetDriverRequest
	(*ListDriversRequest)(nil),   // 3: driver.v1.ListDriversRequest
	(*DeleteDriverRequest)(nil),  // 4: driver.v1.DeleteDriverRequest
	(*CreateDriverResponse)(nil), // 5: driver.v1.CreateDriverResponse
	(*UpdateDriverResponse)(nil), // 6: driver.v1.UpdateDriverResponse
	(*GetDriverResponse)(nil),    // 7: driver.v1.GetDriverResponse
	(*ListDriversResponse)(nil),  // 8: driver.v1.ListDriversResponse
	(*DeleteDriverResponse)(nil), // 9: driver.v1.DeleteDriverResponse
}
var file_driver_v1_service_proto_depIdxs = []int32{
	0, // 0: driver.v1.DriverService.CreateDriver:input_type -> driver.v1.CreateDriverRequest
	1, // 1: driver.v1.DriverService.UpdateDriver:input_type -> driver.v1.UpdateDriverRequest
	2, // 2: driver.v1.DriverService.GetDriver:input_type -> driver.v1.GetDriverRequest
	3, // 3: driver.v1.DriverService.ListDrivers:input_type -> driver.v1.ListDriversRequest
	4, // 4: driver.v1.DriverService.DeleteDriver:input_type -> driver.v1.DeleteDriverRequest
	5, // 5: driver.v1.DriverService.CreateDriver:output_type -> driver.v1.CreateDriverResponse
	6, // 6: driver.v1.DriverService.UpdateDriver:output_type -> driver.v1.UpdateDriverResponse
	7, // 7: driver.v1.DriverService.GetDriver:output_type -> driver.v1.GetDriverResponse
	8, // 8: driver.v1.DriverService.ListDrivers:output_type -> driver.v1.ListDriversResponse
	9, // 9: driver.v1.DriverService.DeleteDriver:output_type -> driver.v1.DeleteDriverResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_driver_v1_service_proto_init() }
func file_driver_v1_service_proto_init() {
	if File_driver_v1_service_proto != nil {
		return
	}
	file_driver_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_driver_v1_service_proto_rawDesc), len(file_driver_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_driver_v1_service_proto_goTypes,
		DependencyIndexes: file_driver_v1_service_proto_depIdxs,
	}.Build()
	File_driver_v1_service_proto = out.File
	file_driver_v1_service_proto_goTypes = nil
	file_driver_v1_service_proto_depIdxs = nil
}
